In [1]:
import numpy as np

In [14]:
class Generator:
    def __init__(self, size_x: int, size_y: int):
        self.generated_list = np.random.rand(size_x, size_y)
        
    def return_sorted(self, reverse: bool = False):
        return np.sort(self.generated_list) if reverse else np.sort(self.generated_list, -1)

In [20]:
generator = Generator(5, 5)

In [23]:
print(f'Созданный массив: {generator.generated_list}')
print(f'Отсортированный массив: {generator.return_sorted()}')
print(f'Отсортированный в обратную сторону массив: {generator.return_sorted(reverse=True)}')

Созданный массив: [[0.01047872 0.08864921 0.59569279 0.34925314 0.42271289]
 [0.28098661 0.80300686 0.83369511 0.19969484 0.5530049 ]
 [0.51271135 0.71308949 0.83282446 0.99916358 0.20707608]
 [0.64068989 0.11407636 0.85128926 0.7159588  0.33938966]
 [0.00521872 0.73567987 0.90689564 0.46748295 0.7912936 ]]
Отсортированный массив: [[0.01047872 0.08864921 0.34925314 0.42271289 0.59569279]
 [0.19969484 0.28098661 0.5530049  0.80300686 0.83369511]
 [0.20707608 0.51271135 0.71308949 0.83282446 0.99916358]
 [0.11407636 0.33938966 0.64068989 0.7159588  0.85128926]
 [0.00521872 0.46748295 0.73567987 0.7912936  0.90689564]]
Отсортированный в обратную сторону массив: [[0.01047872 0.08864921 0.34925314 0.42271289 0.59569279]
 [0.19969484 0.28098661 0.5530049  0.80300686 0.83369511]
 [0.20707608 0.51271135 0.71308949 0.83282446 0.99916358]
 [0.11407636 0.33938966 0.64068989 0.7159588  0.85128926]
 [0.00521872 0.46748295 0.73567987 0.7912936  0.90689564]]
